services:
  app-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php_app
    volumes:
      - ../php-app:/var/www/html
    networks:
      - app-network
  nginx:
    image: nginx:alpine
    container_name: nginx-server
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app-server
    networks:
      - app-network
  angular-front:
    build:
      context: ../my-angular-app
      dockerfile: ../dockerlocal/front/Dockerfile
    container_name: angular_front
    ports:
      - "4200:4200"
    networks:
      - app-network


networks:
  app-network:
    driver: bridge
